#!/bin/sh

# runs tsc --noEmit && eslint src && jest --passWithNoTests
yarn check-all

# run prettier only on staged files
prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown


# if files changed by prettier, add them to the commit
git update-index --again
